#!/bin/bash
# WhatsApp Bot Startup Script

echo "🚀 OptimusGym CRM with WhatsApp Bot"
echo "======================================="
echo ""
echo "This script helps you start both services."
echo ""
echo "✅ Prerequisites:"
echo "   - Node.js installed"
echo "   - npm dependencies installed"
echo "   - .env files configured with API keys"
echo ""
echo "📝 Next Steps:"
echo ""
echo "Terminal 1 - Start WhatsApp Bot Service:"
echo "  $ cd whatsapp-bot"
echo "  $ npm start"
echo ""
echo "Terminal 2 - Start Next.js App (from root):"
echo "  $ npm run dev"
echo ""
echo "📱 Access Application:"
echo "  - App: http://localhost:3000"
echo "  - Bot: http://localhost:3002 (internal)"
echo ""
echo "⚙️  First Time Setup:"
echo "  1. Login as admin to the app"
echo "  2. Go to Settings page"
echo "  3. Configure Gym Timing, Pricing, Diet Plans"
echo "  4. Scroll to WhatsApp Chatbot section"
echo "  5. Enter your WhatsApp phone number"
echo "  6. Follow device linking instructions"
echo ""
echo "✨ Once bot is connected:"
echo "  - Messages to your WhatsApp will get AI replies"
echo "  - Bot includes gym info from your settings"
echo "  - Uses OpenRouter API (gpt-4o-mini model)"
echo ""
echo "📚 Documentation:"
echo "  - OPENROUTER_SETUP.md - Complete setup guide"
echo "  - WHATSAPP_BOT_SETUP.md - Technical details"
echo "  - START_HERE.md - Quick start guide"
echo ""
