export const members = [
  {
    id: "1",
    name: "Rahul Sharma",
    status: "Active",
    plan: "Premium",
    phone: "98765 43210",
    email: "rahul.sharma@email.com",
    address: "23 Green Park, New Delhi",
    emergency: "Amit Sharma - 98765 43211",
    joinDate: "01 Apr 2026",
    expiryDate: "01 Apr 2027",
    remainingDays: 290,
    totalVisits: 45,
    lastVisit: "05 Jun 2026",
    totalPaid: 9000,
    outstanding: 0,
    avatar: "RS",
    avatarColor: "bg-indigo-500",
    planFeatures: ["Gym Access", "Personal Trainer", "Diet Consultation", "Cardio Zone Access"],
    membershipHistory: [
      { plan: "Basic", start: "01 Jan 2026", end: "31 Mar 2026" },
      { plan: "Premium", start: "01 Apr 2026", end: "Current" },
    ],
    membershipTimeline: [
      { label: "Start Date", date: "01 Apr 2026", type: "start" },
      { label: "Renewal History", date: "01 Apr 2026", type: "renewal" },
      { label: "Expiry Date", date: "01 Apr 2027", type: "expiry" },
    ],
    attendanceHistory: [
      { date: "05 Jun 2026", status: "Present" },
      { date: "04 Jun 2026", status: "Present" },
      { date: "03 Jun 2026", status: "Absent" },
      { date: "02 Jun 2026", status: "Present" },
      { date: "01 Jun 2026", status: "Present" },
    ],
    attendanceInsights: { thisMonth: 12, lastVisit: "05 Jun 2026", daysSince: 0 },
    paymentHistory: [
      { date: "01 Jun 2026", amount: 3000, status: "Paid" },
      { date: "01 May 2026", amount: 3000, status: "Paid" },
      { date: "01 Apr 2026", amount: 3000, status: "Paid" },
    ],
    financial: { totalPaid: 9000, pending: 0, lastPayment: "01 Jun 2026" },
    trainerNotes: [
      "Recovering from shoulder injury.",
      "Trainer assigned: Amit.",
      "Avoid heavy overhead exercises.",
    ],
    notesUpdated: "05 Jun 2026 by Amit (Trainer)",
    tags: ["Weight Loss", "Muscle Gain", "Personal Training", "VIP Member"],
  },
  {
    id: "2",
    name: "Aman Singh",
    status: "Active",
    plan: "Premium",
    phone: "98234 56789",
    email: "aman.singh@email.com",
    address: "14 Lajpat Nagar, New Delhi",
    emergency: "Ravi Singh - 98234 56780",
    joinDate: "05 Jun 2026",
    expiryDate: "05 Jun 2027",
    remainingDays: 363,
    totalVisits: 3,
    lastVisit: "07 Jun 2026",
    totalPaid: 4500,
    outstanding: 0,
    avatar: "AS",
    avatarColor: "bg-blue-500",
    planFeatures: ["Gym Access", "Personal Trainer", "Diet Consultation", "Cardio Zone Access"],
    membershipHistory: [
      { plan: "Premium", start: "05 Jun 2026", end: "Current" },
    ],
    membershipTimeline: [
      { label: "Start Date", date: "05 Jun 2026", type: "start" },
      { label: "Expiry Date", date: "05 Jun 2027", type: "expiry" },
    ],
    attendanceHistory: [
      { date: "07 Jun 2026", status: "Present" },
      { date: "06 Jun 2026", status: "Present" },
      { date: "05 Jun 2026", status: "Present" },
    ],
    attendanceInsights: { thisMonth: 3, lastVisit: "07 Jun 2026", daysSince: 0 },
    paymentHistory: [
      { date: "05 Jun 2026", amount: 4500, status: "Paid" },
    ],
    financial: { totalPaid: 4500, pending: 0, lastPayment: "05 Jun 2026" },
    trainerNotes: ["New member. Fitness assessment scheduled.", "Goal: Build muscle mass."],
    notesUpdated: "05 Jun 2026 by Admin",
    tags: ["Muscle Gain", "New Member"],
  },
  {
    id: "3",
    name: "Priya",
    status: "Active",
    plan: "Basic",
    phone: "91234 67890",
    email: "priya.patel@email.com",
    address: "7 Connaught Place, New Delhi",
    emergency: "Suresh Patel - 91234 67891",
    joinDate: "04 Jun 2026",
    expiryDate: "04 Jul 2026",
    remainingDays: 27,
    totalVisits: 8,
    lastVisit: "06 Jun 2026",
    totalPaid: 1500,
    outstanding: 0,
    avatar: "PP",
    avatarColor: "bg-pink-500",
    planFeatures: ["Gym Access", "Cardio Zone Access"],
    membershipHistory: [
      { plan: "Basic", start: "04 Jun 2026", end: "Current" },
    ],
    membershipTimeline: [
      { label: "Start Date", date: "04 Jun 2026", type: "start" },
      { label: "Expiry Date", date: "04 Jul 2026", type: "expiry" },
    ],
    attendanceHistory: [
      { date: "06 Jun 2026", status: "Present" },
      { date: "05 Jun 2026", status: "Absent" },
      { date: "04 Jun 2026", status: "Present" },
      { date: "03 Jun 2026", status: "Present" },
      { date: "02 Jun 2026", status: "Absent" },
    ],
    attendanceInsights: { thisMonth: 6, lastVisit: "06 Jun 2026", daysSince: 1 },
    paymentHistory: [
      { date: "04 Jun 2026", amount: 1500, status: "Paid" },
    ],
    financial: { totalPaid: 1500, pending: 0, lastPayment: "04 Jun 2026" },
    trainerNotes: ["Focused on cardio and flexibility.", "No personal trainer assigned."],
    notesUpdated: "04 Jun 2026 by Admin",
    tags: ["Weight Loss", "Cardio"],
  },
  {
    id: "4",
    name: "Vikram Das",
    status: "Active",
    plan: "Premium",
    phone: "97654 32109",
    email: "vikram.das@email.com",
    address: "55 Vasant Vihar, New Delhi",
    emergency: "Meena Das - 97654 32100",
    joinDate: "01 Jan 2026",
    expiryDate: "25 Jun 2026",
    remainingDays: 18,
    totalVisits: 120,
    lastVisit: "07 Jun 2026",
    totalPaid: 18000,
    outstanding: 2500,
    avatar: "VD",
    avatarColor: "bg-orange-500",
    planFeatures: ["Gym Access", "Personal Trainer", "Diet Consultation", "Cardio Zone Access"],
    membershipHistory: [
      { plan: "Basic", start: "01 Jan 2026", end: "28 Feb 2026" },
      { plan: "Standard", start: "01 Mar 2026", end: "31 Mar 2026" },
      { plan: "Premium", start: "01 Apr 2026", end: "Current" },
    ],
    membershipTimeline: [
      { label: "Start Date", date: "01 Jan 2026", type: "start" },
      { label: "Renewal History", date: "01 Apr 2026", type: "renewal" },
      { label: "Expiry Date", date: "25 Jun 2026", type: "expiry" },
    ],
    attendanceHistory: [
      { date: "07 Jun 2026", status: "Present" },
      { date: "06 Jun 2026", status: "Present" },
      { date: "05 Jun 2026", status: "Present" },
      { date: "04 Jun 2026", status: "Present" },
      { date: "03 Jun 2026", status: "Absent" },
    ],
    attendanceInsights: { thisMonth: 20, lastVisit: "07 Jun 2026", daysSince: 0 },
    paymentHistory: [
      { date: "01 Jun 2026", amount: 4500, status: "Paid" },
      { date: "01 May 2026", amount: 4500, status: "Paid" },
      { date: "01 Apr 2026", amount: 4500, status: "Paid" },
      { date: "18 Jun 2026", amount: 2500, status: "Pending" },
    ],
    financial: { totalPaid: 18000, pending: 2500, lastPayment: "01 Jun 2026" },
    trainerNotes: ["Long-term member. Excellent commitment.", "Working on powerlifting goals."],
    notesUpdated: "07 Jun 2026 by Trainer Raj",
    tags: ["VIP Member", "Powerlifting", "Long-term"],
  },
  {
    id: "5",
    name: "Neha Verma",
    status: "Inactive",
    plan: "Basic",
    phone: "98901 23456",
    email: "neha.verma@email.com",
    address: "3 Saket, New Delhi",
    emergency: "Pooja Verma - 98901 23457",
    joinDate: "01 Mar 2026",
    expiryDate: "31 May 2026",
    remainingDays: 0,
    totalVisits: 22,
    lastVisit: "31 May 2026",
    totalPaid: 3000,
    outstanding: 0,
    avatar: "NV",
    avatarColor: "bg-purple-500",
    planFeatures: ["Gym Access"],
    membershipHistory: [
      { plan: "Basic", start: "01 Mar 2026", end: "31 May 2026" },
    ],
    membershipTimeline: [
      { label: "Start Date", date: "01 Mar 2026", type: "start" },
      { label: "Expiry Date", date: "31 May 2026", type: "expiry" },
    ],
    attendanceHistory: [
      { date: "31 May 2026", status: "Present" },
      { date: "30 May 2026", status: "Absent" },
      { date: "29 May 2026", status: "Absent" },
      { date: "28 May 2026", status: "Present" },
      { date: "27 May 2026", status: "Absent" },
    ],
    attendanceInsights: { thisMonth: 4, lastVisit: "31 May 2026", daysSince: 7 },
    paymentHistory: [
      { date: "01 Mar 2026", amount: 1500, status: "Paid" },
      { date: "01 Apr 2026", amount: 1500, status: "Paid" },
    ],
    financial: { totalPaid: 3000, pending: 0, lastPayment: "01 Apr 2026" },
    trainerNotes: ["Membership expired. Needs renewal follow-up."],
    notesUpdated: "01 Jun 2026 by Admin",
    tags: ["Renewal Pending"],
  },
  {
    id: "6",
    name: "Rohit Verma",
    status: "Active",
    plan: "Standard",
    phone: "99887 76655",
    email: "rohit.verma@email.com",
    address: "88 Dwarka Sector 12, New Delhi",
    emergency: "Anita Verma - 99887 76656",
    joinDate: "03 Jun 2026",
    expiryDate: "03 Dec 2026",
    remainingDays: 179,
    totalVisits: 5,
    lastVisit: "07 Jun 2026",
    totalPaid: 3000,
    outstanding: 0,
    avatar: "RV",
    avatarColor: "bg-green-500",
    planFeatures: ["Gym Access", "Diet Consultation", "Cardio Zone Access"],
    membershipHistory: [
      { plan: "Standard", start: "03 Jun 2026", end: "Current" },
    ],
    membershipTimeline: [
      { label: "Start Date", date: "03 Jun 2026", type: "start" },
      { label: "Expiry Date", date: "03 Dec 2026", type: "expiry" },
    ],
    attendanceHistory: [
      { date: "07 Jun 2026", status: "Present" },
      { date: "06 Jun 2026", status: "Present" },
      { date: "05 Jun 2026", status: "Absent" },
      { date: "04 Jun 2026", status: "Present" },
      { date: "03 Jun 2026", status: "Present" },
    ],
    attendanceInsights: { thisMonth: 4, lastVisit: "07 Jun 2026", daysSince: 0 },
    paymentHistory: [
      { date: "03 Jun 2026", amount: 3000, status: "Paid" },
    ],
    financial: { totalPaid: 3000, pending: 0, lastPayment: "03 Jun 2026" },
    trainerNotes: ["Standard plan with balanced goals."],
    notesUpdated: "07 Jun 2026 by Admin",
    tags: ["Standard Member", "Diet Plan"],
  },
];
